services:
  trainer:
    build:
      context: ..
      dockerfile: ML-Agents/Dockerfile
    container_name: mlagents-trainer
    working_dir: /workspace
    volumes:
      - ..:/workspace
    tty: true
    stdin_open: true
    ports:
      - "5004:5004"
